POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhzZGYiLCJpZCI6IjVmNWI3ZWFlOWI5MGU0NmUwZmZiOGFiNSIsImlhdCI6MTU5OTgzMTg4Mn0.dfHBc7EouHXl1pLVs88V9AIAx6I-CqI9wWag5xP7Cyw

{
    "title": "bla",
    "author": "true",
    "url": "sf",
    "likes": 5,
    "userId": "5fae839109fdc8861f722188",
    "comments": []
}